# Generated by Django 4.2.4 on 2023-08-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_created_by_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='question1',
        ),
    ]
