# Generated by Django 4.2.4 on 2023-08-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_question_quiz_question1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question1',
            new_name='question',
        ),
    ]
